import type { Component } from 'vue'
import {
  AccountBookOutlined,
  AimOutlined,
  AlertOutlined,
  AlibabaOutlined,
  AlignCenterOutlined,
  AlignLeftOutlined,
  AlignRightOutlined,
  AlipayCircleOutlined,
  AlipayOutlined,
  AliwangwangOutlined,
  AliyunOutlined,
  AmazonOutlined,
  AndroidOutlined,
  AntCloudOutlined,
  AntDesignOutlined,
  ApartmentOutlined,
  ApiOutlined,
  AppleOutlined,
  AppstoreAddOutlined,
  AppstoreOutlined,
  AreaChartOutlined,
  ArrowDownOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  ArrowUpOutlined,
  ArrowsAltOutlined,
  AudioMutedOutlined,
  AudioOutlined,
  AuditOutlined,
  BackwardOutlined,
  BankOutlined,
  BarChartOutlined,
  BarcodeOutlined,
  BarsOutlined,
  BehanceOutlined,
  BehanceSquareOutlined,
  BellOutlined,
  BgColorsOutlined,
  BlockOutlined,
  BoldOutlined,
  BookOutlined,
  BorderBottomOutlined,
  BorderHorizontalOutlined,
  BorderInnerOutlined,
  BorderLeftOutlined,
  BorderOuterOutlined,
  BorderOutlined,
  BorderRightOutlined,
  BorderTopOutlined,
  BorderVerticleOutlined,
  BorderlessTableOutlined,
  BoxPlotOutlined,
  BranchesOutlined,
  BugOutlined,
  BuildOutlined,
  BulbOutlined,
  CalculatorOutlined,
  CalendarOutlined,
  CameraOutlined,
  CarOutlined,
  CaretDownOutlined,
  CaretLeftOutlined,
  CaretRightOutlined,
  CaretUpOutlined,
  CarryOutOutlined,
  CheckCircleOutlined,
  CheckOutlined,
  CheckSquareOutlined,
  ChromeOutlined,
  CiCircleOutlined,
  CiOutlined,
  ClearOutlined,
  ClockCircleOutlined,
  CloseCircleOutlined,
  CloseOutlined,
  CloseSquareOutlined,
  CloudDownloadOutlined,
  CloudOutlined,
  CloudServerOutlined,
  CloudSyncOutlined,
  CloudUploadOutlined,
  ClusterOutlined,
  CodeOutlined,
  CodeSandboxOutlined,
  CodepenCircleOutlined,
  CodepenOutlined,
  CoffeeOutlined,
  ColumnHeightOutlined,
  ColumnWidthOutlined,
  CommentOutlined,
  CompassOutlined,
  CompressOutlined,
  ConsoleSqlOutlined,
  ContactsOutlined,
  ContainerOutlined,
  ControlOutlined,
  CopyOutlined,
  CopyrightCircleOutlined,
  CopyrightOutlined,
  CreditCardOutlined,
  CrownOutlined,
  CustomerServiceOutlined,
  DashOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DeleteColumnOutlined,
  DeleteOutlined,
  DeleteRowOutlined,
  DeliveredProcedureOutlined,
  DeploymentUnitOutlined,
  DesktopOutlined,
  DiffOutlined,
  DingdingOutlined,
  DingtalkOutlined,
  DisconnectOutlined,
  DislikeOutlined,
  DollarCircleOutlined,
  DollarOutlined,
  DotChartOutlined,
  DoubleLeftOutlined,
  DoubleRightOutlined,
  DownCircleOutlined,
  DownOutlined,
  DownSquareOutlined,
  DownloadOutlined,
  DragOutlined,
  DribbbleOutlined,
  DribbbleSquareOutlined,
  DropboxOutlined,
  EditOutlined,
  EllipsisOutlined,
  EnterOutlined,
  EnvironmentOutlined,
  EuroCircleOutlined,
  EuroOutlined,
  ExceptionOutlined,
  ExclamationCircleOutlined,
  ExclamationOutlined,
  ExpandAltOutlined,
  ExpandOutlined,
  ExperimentOutlined,
  ExportOutlined,
  EyeInvisibleOutlined,
  EyeOutlined,
  FacebookOutlined,
  FallOutlined,
  FastBackwardOutlined,
  FastForwardOutlined,
  FieldBinaryOutlined,
  FieldNumberOutlined,
  FieldStringOutlined,
  FieldTimeOutlined,
  FileAddOutlined,
  FileDoneOutlined,
  FileExcelOutlined,
  FileExclamationOutlined,
  FileGifOutlined,
  FileImageOutlined,
  FileJpgOutlined,
  FileMarkdownOutlined,
  FileOutlined,
  FilePdfOutlined,
  FilePptOutlined,
  FileProtectOutlined,
  FileSearchOutlined,
  FileSyncOutlined,
  FileTextOutlined,
  FileUnknownOutlined,
  FileWordOutlined,
  FileZipOutlined,
  FilterOutlined,
  FireOutlined,
  FlagOutlined,
  FolderAddOutlined,
  FolderOpenOutlined,
  FolderOutlined,
  FolderViewOutlined,
  FontColorsOutlined,
  FontSizeOutlined,
  ForkOutlined,
  FormOutlined,
  FormatPainterOutlined,
  ForwardOutlined,
  FrownOutlined,
  FullscreenExitOutlined,
  FullscreenOutlined,
  FunctionOutlined,
  FundOutlined,
  FundProjectionScreenOutlined,
  FundViewOutlined,
  FunnelPlotOutlined,
  GatewayOutlined,
  GifOutlined,
  GiftOutlined,
  GithubOutlined,
  GitlabOutlined,
  GlobalOutlined,
  GoldOutlined,
  GoogleOutlined,
  GooglePlusOutlined,
  GroupOutlined,
  HddOutlined,
  HeartOutlined,
  HeatMapOutlined,
  HighlightOutlined,
  HistoryOutlined,
  HolderOutlined,
  HomeOutlined,
  HourglassOutlined,
  Html5Outlined,
  IdcardOutlined,
  IeOutlined,
  ImportOutlined,
  InboxOutlined,
  InfoCircleOutlined,
  InfoOutlined,
  InsertRowAboveOutlined,
  InsertRowBelowOutlined,
  InsertRowLeftOutlined,
  InsertRowRightOutlined,
  InstagramOutlined,
  InsuranceOutlined,
  InteractionOutlined,
  IssuesCloseOutlined,
  ItalicOutlined,
  KeyOutlined,
  LaptopOutlined,
  LayoutOutlined,
  LeftCircleOutlined,
  LeftOutlined,
  LeftSquareOutlined,
  LikeOutlined,
  LineChartOutlined,
  LineHeightOutlined,
  LineOutlined,
  LinkOutlined,
  LinkedinOutlined,
  Loading3QuartersOutlined,
  LoadingOutlined,
  LockOutlined,
  LoginOutlined,
  LogoutOutlined,
  MacCommandOutlined,
  MailOutlined,
  ManOutlined,
  MedicineBoxOutlined,
  MediumOutlined,
  MediumWorkmarkOutlined,
  MehOutlined,
  MenuFoldOutlined,
  MenuOutlined,
  MenuUnfoldOutlined,
  MergeCellsOutlined,
  MessageOutlined,
  MinusCircleOutlined,
  MinusOutlined,
  MinusSquareOutlined,
  MobileOutlined,
  MoneyCollectOutlined,
  MonitorOutlined,
  MoreOutlined,
  NodeCollapseOutlined,
  NodeExpandOutlined,
  NodeIndexOutlined,
  NotificationOutlined,
  NumberOutlined,
  OneToOneOutlined,
  OrderedListOutlined,
  PaperClipOutlined,
  PartitionOutlined,
  PauseCircleOutlined,
  PauseOutlined,
  PayCircleOutlined,
  PercentageOutlined,
  PhoneOutlined,
  PicCenterOutlined,
  PicLeftOutlined,
  PicRightOutlined,
  PictureOutlined,
  PieChartOutlined,
  PlayCircleOutlined,
  PlaySquareOutlined,
  PlusCircleOutlined,
  PlusOutlined,
  PlusSquareOutlined,
  PoundCircleOutlined,
  PoundOutlined,
  PoweroffOutlined,
  PrinterOutlined,
  ProfileOutlined,
  ProjectOutlined,
  PropertySafetyOutlined,
  PullRequestOutlined,
  PushpinOutlined,
  QqOutlined,
  QrcodeOutlined,
  QuestionCircleOutlined,
  QuestionOutlined,
  RadarChartOutlined,
  RadiusBottomleftOutlined,
  RadiusBottomrightOutlined,
  RadiusSettingOutlined,
  RadiusUpleftOutlined,
  RadiusUprightOutlined,
  ReadOutlined,
  ReconciliationOutlined,
  RedEnvelopeOutlined,
  RedditOutlined,
  RedoOutlined,
  ReloadOutlined,
  RestOutlined,
  RetweetOutlined,
  RightCircleOutlined,
  RightOutlined,
  RightSquareOutlined,
  RiseOutlined,
  RobotOutlined,
  RocketOutlined,
  RollbackOutlined,
  RotateLeftOutlined,
  RotateRightOutlined,
  SafetyCertificateOutlined,
  SafetyOutlined,
  SaveOutlined,
  ScanOutlined,
  ScheduleOutlined,
  ScissorOutlined,
  SearchOutlined,
  SecurityScanOutlined,
  SelectOutlined,
  SendOutlined,
  SettingOutlined,
  ShakeOutlined,
  ShareAltOutlined,
  ShopOutlined,
  ShoppingCartOutlined,
  ShoppingOutlined,
  ShrinkOutlined,
  SisternodeOutlined,
  SketchOutlined,
  SkinOutlined,
  SkypeOutlined,
  SlackOutlined,
  SlackSquareOutlined,
  SlidersOutlined,
  SmallDashOutlined,
  SmileOutlined,
  SnippetsOutlined,
  SolutionOutlined,
  SortAscendingOutlined,
  SortDescendingOutlined,
  SoundOutlined,
  SplitCellsOutlined,
  StarOutlined,
  StepBackwardOutlined,
  StepForwardOutlined,
  StockOutlined,
  StopOutlined,
  StrikethroughOutlined,
  SubnodeOutlined,
  SwapLeftOutlined,
  SwapOutlined,
  SwapRightOutlined,
  SwitcherOutlined,
  SyncOutlined,
  TableOutlined,
  TabletOutlined,
  TagOutlined,
  TagsOutlined,
  TaobaoCircleOutlined,
  TaobaoOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  ToTopOutlined,
  ToolOutlined,
  TrademarkCircleOutlined,
  TrademarkOutlined,
  TransactionOutlined,
  TranslationOutlined,
  TrophyOutlined,
  TwitterOutlined,
  UnderlineOutlined,
  UndoOutlined,
  UngroupOutlined,
  UnlockOutlined,
  UnorderedListOutlined,
  UpCircleOutlined,
  UpOutlined,
  UpSquareOutlined,
  UploadOutlined,
  UsbOutlined,
  UserAddOutlined,
  UserDeleteOutlined,
  UserOutlined,
  UserSwitchOutlined,
  UsergroupAddOutlined,
  UsergroupDeleteOutlined,
  VerifiedOutlined,
  VerticalAlignBottomOutlined,
  VerticalAlignMiddleOutlined,
  VerticalAlignTopOutlined,
  VerticalLeftOutlined,
  VerticalRightOutlined,
  VideoCameraAddOutlined,
  VideoCameraOutlined,
  WalletOutlined,
  WarningOutlined,
  WechatOutlined,
  WeiboCircleOutlined,
  WeiboOutlined,
  WeiboSquareOutlined,
  WhatsAppOutlined,
  WifiOutlined,
  WindowsOutlined,
  WomanOutlined,
  YahooOutlined,
  YoutubeOutlined,
  YuqueOutlined,
  ZhihuOutlined,
  ZoomInOutlined,
  ZoomOutOutlined,
} from '@ant-design/icons-vue'

export type IconCategoryKey =
  | 'common'
  | 'document'
  | 'work'
  | 'data'
  | 'dev'
  | 'editor'
  | 'media'
  | 'communication'
  | 'navigation'
  | 'status'
  | 'brand'
  | 'all'

export type SelectableIconCategoryKey = Exclude<IconCategoryKey, 'all'>

export const iconCategories: Array<{ key: IconCategoryKey; label: string }> = [
  { key: 'common', label: '\u5e38\u7528' },
  { key: 'document', label: '\u6587\u6863' },
  { key: 'work', label: '\u5de5\u4f5c' },
  { key: 'data', label: '\u6570\u636e' },
  { key: 'dev', label: '\u5f00\u53d1' },
  { key: 'editor', label: '\u7f16\u8f91' },
  { key: 'media', label: '\u5a92\u4f53' },
  { key: 'communication', label: '\u6c9f\u901a' },
  { key: 'navigation', label: '\u5bfc\u822a' },
  { key: 'status', label: '\u72b6\u6001' },
  { key: 'brand', label: '\u54c1\u724c' },
  { key: 'all', label: '\u5168\u90e8' },
]

const componentMap = {
  AccountBookOutlined,
  AimOutlined,
  AlertOutlined,
  AlibabaOutlined,
  AlignCenterOutlined,
  AlignLeftOutlined,
  AlignRightOutlined,
  AlipayCircleOutlined,
  AlipayOutlined,
  AliwangwangOutlined,
  AliyunOutlined,
  AmazonOutlined,
  AndroidOutlined,
  AntCloudOutlined,
  AntDesignOutlined,
  ApartmentOutlined,
  ApiOutlined,
  AppleOutlined,
  AppstoreAddOutlined,
  AppstoreOutlined,
  AreaChartOutlined,
  ArrowDownOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  ArrowUpOutlined,
  ArrowsAltOutlined,
  AudioMutedOutlined,
  AudioOutlined,
  AuditOutlined,
  BackwardOutlined,
  BankOutlined,
  BarChartOutlined,
  BarcodeOutlined,
  BarsOutlined,
  BehanceOutlined,
  BehanceSquareOutlined,
  BellOutlined,
  BgColorsOutlined,
  BlockOutlined,
  BoldOutlined,
  BookOutlined,
  BorderBottomOutlined,
  BorderHorizontalOutlined,
  BorderInnerOutlined,
  BorderLeftOutlined,
  BorderOuterOutlined,
  BorderOutlined,
  BorderRightOutlined,
  BorderTopOutlined,
  BorderVerticleOutlined,
  BorderlessTableOutlined,
  BoxPlotOutlined,
  BranchesOutlined,
  BugOutlined,
  BuildOutlined,
  BulbOutlined,
  CalculatorOutlined,
  CalendarOutlined,
  CameraOutlined,
  CarOutlined,
  CaretDownOutlined,
  CaretLeftOutlined,
  CaretRightOutlined,
  CaretUpOutlined,
  CarryOutOutlined,
  CheckCircleOutlined,
  CheckOutlined,
  CheckSquareOutlined,
  ChromeOutlined,
  CiCircleOutlined,
  CiOutlined,
  ClearOutlined,
  ClockCircleOutlined,
  CloseCircleOutlined,
  CloseOutlined,
  CloseSquareOutlined,
  CloudDownloadOutlined,
  CloudOutlined,
  CloudServerOutlined,
  CloudSyncOutlined,
  CloudUploadOutlined,
  ClusterOutlined,
  CodeOutlined,
  CodeSandboxOutlined,
  CodepenCircleOutlined,
  CodepenOutlined,
  CoffeeOutlined,
  ColumnHeightOutlined,
  ColumnWidthOutlined,
  CommentOutlined,
  CompassOutlined,
  CompressOutlined,
  ConsoleSqlOutlined,
  ContactsOutlined,
  ContainerOutlined,
  ControlOutlined,
  CopyOutlined,
  CopyrightCircleOutlined,
  CopyrightOutlined,
  CreditCardOutlined,
  CrownOutlined,
  CustomerServiceOutlined,
  DashOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DeleteColumnOutlined,
  DeleteOutlined,
  DeleteRowOutlined,
  DeliveredProcedureOutlined,
  DeploymentUnitOutlined,
  DesktopOutlined,
  DiffOutlined,
  DingdingOutlined,
  DingtalkOutlined,
  DisconnectOutlined,
  DislikeOutlined,
  DollarCircleOutlined,
  DollarOutlined,
  DotChartOutlined,
  DoubleLeftOutlined,
  DoubleRightOutlined,
  DownCircleOutlined,
  DownOutlined,
  DownSquareOutlined,
  DownloadOutlined,
  DragOutlined,
  DribbbleOutlined,
  DribbbleSquareOutlined,
  DropboxOutlined,
  EditOutlined,
  EllipsisOutlined,
  EnterOutlined,
  EnvironmentOutlined,
  EuroCircleOutlined,
  EuroOutlined,
  ExceptionOutlined,
  ExclamationCircleOutlined,
  ExclamationOutlined,
  ExpandAltOutlined,
  ExpandOutlined,
  ExperimentOutlined,
  ExportOutlined,
  EyeInvisibleOutlined,
  EyeOutlined,
  FacebookOutlined,
  FallOutlined,
  FastBackwardOutlined,
  FastForwardOutlined,
  FieldBinaryOutlined,
  FieldNumberOutlined,
  FieldStringOutlined,
  FieldTimeOutlined,
  FileAddOutlined,
  FileDoneOutlined,
  FileExcelOutlined,
  FileExclamationOutlined,
  FileGifOutlined,
  FileImageOutlined,
  FileJpgOutlined,
  FileMarkdownOutlined,
  FileOutlined,
  FilePdfOutlined,
  FilePptOutlined,
  FileProtectOutlined,
  FileSearchOutlined,
  FileSyncOutlined,
  FileTextOutlined,
  FileUnknownOutlined,
  FileWordOutlined,
  FileZipOutlined,
  FilterOutlined,
  FireOutlined,
  FlagOutlined,
  FolderAddOutlined,
  FolderOpenOutlined,
  FolderOutlined,
  FolderViewOutlined,
  FontColorsOutlined,
  FontSizeOutlined,
  ForkOutlined,
  FormOutlined,
  FormatPainterOutlined,
  ForwardOutlined,
  FrownOutlined,
  FullscreenExitOutlined,
  FullscreenOutlined,
  FunctionOutlined,
  FundOutlined,
  FundProjectionScreenOutlined,
  FundViewOutlined,
  FunnelPlotOutlined,
  GatewayOutlined,
  GifOutlined,
  GiftOutlined,
  GithubOutlined,
  GitlabOutlined,
  GlobalOutlined,
  GoldOutlined,
  GoogleOutlined,
  GooglePlusOutlined,
  GroupOutlined,
  HddOutlined,
  HeartOutlined,
  HeatMapOutlined,
  HighlightOutlined,
  HistoryOutlined,
  HolderOutlined,
  HomeOutlined,
  HourglassOutlined,
  Html5Outlined,
  IdcardOutlined,
  IeOutlined,
  ImportOutlined,
  InboxOutlined,
  InfoCircleOutlined,
  InfoOutlined,
  InsertRowAboveOutlined,
  InsertRowBelowOutlined,
  InsertRowLeftOutlined,
  InsertRowRightOutlined,
  InstagramOutlined,
  InsuranceOutlined,
  InteractionOutlined,
  IssuesCloseOutlined,
  ItalicOutlined,
  KeyOutlined,
  LaptopOutlined,
  LayoutOutlined,
  LeftCircleOutlined,
  LeftOutlined,
  LeftSquareOutlined,
  LikeOutlined,
  LineChartOutlined,
  LineHeightOutlined,
  LineOutlined,
  LinkOutlined,
  LinkedinOutlined,
  Loading3QuartersOutlined,
  LoadingOutlined,
  LockOutlined,
  LoginOutlined,
  LogoutOutlined,
  MacCommandOutlined,
  MailOutlined,
  ManOutlined,
  MedicineBoxOutlined,
  MediumOutlined,
  MediumWorkmarkOutlined,
  MehOutlined,
  MenuFoldOutlined,
  MenuOutlined,
  MenuUnfoldOutlined,
  MergeCellsOutlined,
  MessageOutlined,
  MinusCircleOutlined,
  MinusOutlined,
  MinusSquareOutlined,
  MobileOutlined,
  MoneyCollectOutlined,
  MonitorOutlined,
  MoreOutlined,
  NodeCollapseOutlined,
  NodeExpandOutlined,
  NodeIndexOutlined,
  NotificationOutlined,
  NumberOutlined,
  OneToOneOutlined,
  OrderedListOutlined,
  PaperClipOutlined,
  PartitionOutlined,
  PauseCircleOutlined,
  PauseOutlined,
  PayCircleOutlined,
  PercentageOutlined,
  PhoneOutlined,
  PicCenterOutlined,
  PicLeftOutlined,
  PicRightOutlined,
  PictureOutlined,
  PieChartOutlined,
  PlayCircleOutlined,
  PlaySquareOutlined,
  PlusCircleOutlined,
  PlusOutlined,
  PlusSquareOutlined,
  PoundCircleOutlined,
  PoundOutlined,
  PoweroffOutlined,
  PrinterOutlined,
  ProfileOutlined,
  ProjectOutlined,
  PropertySafetyOutlined,
  PullRequestOutlined,
  PushpinOutlined,
  QqOutlined,
  QrcodeOutlined,
  QuestionCircleOutlined,
  QuestionOutlined,
  RadarChartOutlined,
  RadiusBottomleftOutlined,
  RadiusBottomrightOutlined,
  RadiusSettingOutlined,
  RadiusUpleftOutlined,
  RadiusUprightOutlined,
  ReadOutlined,
  ReconciliationOutlined,
  RedEnvelopeOutlined,
  RedditOutlined,
  RedoOutlined,
  ReloadOutlined,
  RestOutlined,
  RetweetOutlined,
  RightCircleOutlined,
  RightOutlined,
  RightSquareOutlined,
  RiseOutlined,
  RobotOutlined,
  RocketOutlined,
  RollbackOutlined,
  RotateLeftOutlined,
  RotateRightOutlined,
  SafetyCertificateOutlined,
  SafetyOutlined,
  SaveOutlined,
  ScanOutlined,
  ScheduleOutlined,
  ScissorOutlined,
  SearchOutlined,
  SecurityScanOutlined,
  SelectOutlined,
  SendOutlined,
  SettingOutlined,
  ShakeOutlined,
  ShareAltOutlined,
  ShopOutlined,
  ShoppingCartOutlined,
  ShoppingOutlined,
  ShrinkOutlined,
  SisternodeOutlined,
  SketchOutlined,
  SkinOutlined,
  SkypeOutlined,
  SlackOutlined,
  SlackSquareOutlined,
  SlidersOutlined,
  SmallDashOutlined,
  SmileOutlined,
  SnippetsOutlined,
  SolutionOutlined,
  SortAscendingOutlined,
  SortDescendingOutlined,
  SoundOutlined,
  SplitCellsOutlined,
  StarOutlined,
  StepBackwardOutlined,
  StepForwardOutlined,
  StockOutlined,
  StopOutlined,
  StrikethroughOutlined,
  SubnodeOutlined,
  SwapLeftOutlined,
  SwapOutlined,
  SwapRightOutlined,
  SwitcherOutlined,
  SyncOutlined,
  TableOutlined,
  TabletOutlined,
  TagOutlined,
  TagsOutlined,
  TaobaoCircleOutlined,
  TaobaoOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  ToTopOutlined,
  ToolOutlined,
  TrademarkCircleOutlined,
  TrademarkOutlined,
  TransactionOutlined,
  TranslationOutlined,
  TrophyOutlined,
  TwitterOutlined,
  UnderlineOutlined,
  UndoOutlined,
  UngroupOutlined,
  UnlockOutlined,
  UnorderedListOutlined,
  UpCircleOutlined,
  UpOutlined,
  UpSquareOutlined,
  UploadOutlined,
  UsbOutlined,
  UserAddOutlined,
  UserDeleteOutlined,
  UserOutlined,
  UserSwitchOutlined,
  UsergroupAddOutlined,
  UsergroupDeleteOutlined,
  VerifiedOutlined,
  VerticalAlignBottomOutlined,
  VerticalAlignMiddleOutlined,
  VerticalAlignTopOutlined,
  VerticalLeftOutlined,
  VerticalRightOutlined,
  VideoCameraAddOutlined,
  VideoCameraOutlined,
  WalletOutlined,
  WarningOutlined,
  WechatOutlined,
  WeiboCircleOutlined,
  WeiboOutlined,
  WeiboSquareOutlined,
  WhatsAppOutlined,
  WifiOutlined,
  WindowsOutlined,
  WomanOutlined,
  YahooOutlined,
  YoutubeOutlined,
  YuqueOutlined,
  ZhihuOutlined,
  ZoomInOutlined,
  ZoomOutOutlined,
} as Record<OutlineIconName, Component>

const outlinedIconNames = [
  'AccountBookOutlined',
  'AimOutlined',
  'AlertOutlined',
  'AlibabaOutlined',
  'AlignCenterOutlined',
  'AlignLeftOutlined',
  'AlignRightOutlined',
  'AlipayCircleOutlined',
  'AlipayOutlined',
  'AliwangwangOutlined',
  'AliyunOutlined',
  'AmazonOutlined',
  'AndroidOutlined',
  'AntCloudOutlined',
  'AntDesignOutlined',
  'ApartmentOutlined',
  'ApiOutlined',
  'AppleOutlined',
  'AppstoreAddOutlined',
  'AppstoreOutlined',
  'AreaChartOutlined',
  'ArrowDownOutlined',
  'ArrowLeftOutlined',
  'ArrowRightOutlined',
  'ArrowUpOutlined',
  'ArrowsAltOutlined',
  'AudioMutedOutlined',
  'AudioOutlined',
  'AuditOutlined',
  'BackwardOutlined',
  'BankOutlined',
  'BarChartOutlined',
  'BarcodeOutlined',
  'BarsOutlined',
  'BehanceOutlined',
  'BehanceSquareOutlined',
  'BellOutlined',
  'BgColorsOutlined',
  'BlockOutlined',
  'BoldOutlined',
  'BookOutlined',
  'BorderBottomOutlined',
  'BorderHorizontalOutlined',
  'BorderInnerOutlined',
  'BorderLeftOutlined',
  'BorderOuterOutlined',
  'BorderOutlined',
  'BorderRightOutlined',
  'BorderTopOutlined',
  'BorderVerticleOutlined',
  'BorderlessTableOutlined',
  'BoxPlotOutlined',
  'BranchesOutlined',
  'BugOutlined',
  'BuildOutlined',
  'BulbOutlined',
  'CalculatorOutlined',
  'CalendarOutlined',
  'CameraOutlined',
  'CarOutlined',
  'CaretDownOutlined',
  'CaretLeftOutlined',
  'CaretRightOutlined',
  'CaretUpOutlined',
  'CarryOutOutlined',
  'CheckCircleOutlined',
  'CheckOutlined',
  'CheckSquareOutlined',
  'ChromeOutlined',
  'CiCircleOutlined',
  'CiOutlined',
  'ClearOutlined',
  'ClockCircleOutlined',
  'CloseCircleOutlined',
  'CloseOutlined',
  'CloseSquareOutlined',
  'CloudDownloadOutlined',
  'CloudOutlined',
  'CloudServerOutlined',
  'CloudSyncOutlined',
  'CloudUploadOutlined',
  'ClusterOutlined',
  'CodeOutlined',
  'CodeSandboxOutlined',
  'CodepenCircleOutlined',
  'CodepenOutlined',
  'CoffeeOutlined',
  'ColumnHeightOutlined',
  'ColumnWidthOutlined',
  'CommentOutlined',
  'CompassOutlined',
  'CompressOutlined',
  'ConsoleSqlOutlined',
  'ContactsOutlined',
  'ContainerOutlined',
  'ControlOutlined',
  'CopyOutlined',
  'CopyrightCircleOutlined',
  'CopyrightOutlined',
  'CreditCardOutlined',
  'CrownOutlined',
  'CustomerServiceOutlined',
  'DashOutlined',
  'DashboardOutlined',
  'DatabaseOutlined',
  'DeleteColumnOutlined',
  'DeleteOutlined',
  'DeleteRowOutlined',
  'DeliveredProcedureOutlined',
  'DeploymentUnitOutlined',
  'DesktopOutlined',
  'DiffOutlined',
  'DingdingOutlined',
  'DingtalkOutlined',
  'DisconnectOutlined',
  'DislikeOutlined',
  'DollarCircleOutlined',
  'DollarOutlined',
  'DotChartOutlined',
  'DoubleLeftOutlined',
  'DoubleRightOutlined',
  'DownCircleOutlined',
  'DownOutlined',
  'DownSquareOutlined',
  'DownloadOutlined',
  'DragOutlined',
  'DribbbleOutlined',
  'DribbbleSquareOutlined',
  'DropboxOutlined',
  'EditOutlined',
  'EllipsisOutlined',
  'EnterOutlined',
  'EnvironmentOutlined',
  'EuroCircleOutlined',
  'EuroOutlined',
  'ExceptionOutlined',
  'ExclamationCircleOutlined',
  'ExclamationOutlined',
  'ExpandAltOutlined',
  'ExpandOutlined',
  'ExperimentOutlined',
  'ExportOutlined',
  'EyeInvisibleOutlined',
  'EyeOutlined',
  'FacebookOutlined',
  'FallOutlined',
  'FastBackwardOutlined',
  'FastForwardOutlined',
  'FieldBinaryOutlined',
  'FieldNumberOutlined',
  'FieldStringOutlined',
  'FieldTimeOutlined',
  'FileAddOutlined',
  'FileDoneOutlined',
  'FileExcelOutlined',
  'FileExclamationOutlined',
  'FileGifOutlined',
  'FileImageOutlined',
  'FileJpgOutlined',
  'FileMarkdownOutlined',
  'FileOutlined',
  'FilePdfOutlined',
  'FilePptOutlined',
  'FileProtectOutlined',
  'FileSearchOutlined',
  'FileSyncOutlined',
  'FileTextOutlined',
  'FileUnknownOutlined',
  'FileWordOutlined',
  'FileZipOutlined',
  'FilterOutlined',
  'FireOutlined',
  'FlagOutlined',
  'FolderAddOutlined',
  'FolderOpenOutlined',
  'FolderOutlined',
  'FolderViewOutlined',
  'FontColorsOutlined',
  'FontSizeOutlined',
  'ForkOutlined',
  'FormOutlined',
  'FormatPainterOutlined',
  'ForwardOutlined',
  'FrownOutlined',
  'FullscreenExitOutlined',
  'FullscreenOutlined',
  'FunctionOutlined',
  'FundOutlined',
  'FundProjectionScreenOutlined',
  'FundViewOutlined',
  'FunnelPlotOutlined',
  'GatewayOutlined',
  'GifOutlined',
  'GiftOutlined',
  'GithubOutlined',
  'GitlabOutlined',
  'GlobalOutlined',
  'GoldOutlined',
  'GoogleOutlined',
  'GooglePlusOutlined',
  'GroupOutlined',
  'HddOutlined',
  'HeartOutlined',
  'HeatMapOutlined',
  'HighlightOutlined',
  'HistoryOutlined',
  'HolderOutlined',
  'HomeOutlined',
  'HourglassOutlined',
  'Html5Outlined',
  'IdcardOutlined',
  'IeOutlined',
  'ImportOutlined',
  'InboxOutlined',
  'InfoCircleOutlined',
  'InfoOutlined',
  'InsertRowAboveOutlined',
  'InsertRowBelowOutlined',
  'InsertRowLeftOutlined',
  'InsertRowRightOutlined',
  'InstagramOutlined',
  'InsuranceOutlined',
  'InteractionOutlined',
  'IssuesCloseOutlined',
  'ItalicOutlined',
  'KeyOutlined',
  'LaptopOutlined',
  'LayoutOutlined',
  'LeftCircleOutlined',
  'LeftOutlined',
  'LeftSquareOutlined',
  'LikeOutlined',
  'LineChartOutlined',
  'LineHeightOutlined',
  'LineOutlined',
  'LinkOutlined',
  'LinkedinOutlined',
  'Loading3QuartersOutlined',
  'LoadingOutlined',
  'LockOutlined',
  'LoginOutlined',
  'LogoutOutlined',
  'MacCommandOutlined',
  'MailOutlined',
  'ManOutlined',
  'MedicineBoxOutlined',
  'MediumOutlined',
  'MediumWorkmarkOutlined',
  'MehOutlined',
  'MenuFoldOutlined',
  'MenuOutlined',
  'MenuUnfoldOutlined',
  'MergeCellsOutlined',
  'MessageOutlined',
  'MinusCircleOutlined',
  'MinusOutlined',
  'MinusSquareOutlined',
  'MobileOutlined',
  'MoneyCollectOutlined',
  'MonitorOutlined',
  'MoreOutlined',
  'NodeCollapseOutlined',
  'NodeExpandOutlined',
  'NodeIndexOutlined',
  'NotificationOutlined',
  'NumberOutlined',
  'OneToOneOutlined',
  'OrderedListOutlined',
  'PaperClipOutlined',
  'PartitionOutlined',
  'PauseCircleOutlined',
  'PauseOutlined',
  'PayCircleOutlined',
  'PercentageOutlined',
  'PhoneOutlined',
  'PicCenterOutlined',
  'PicLeftOutlined',
  'PicRightOutlined',
  'PictureOutlined',
  'PieChartOutlined',
  'PlayCircleOutlined',
  'PlaySquareOutlined',
  'PlusCircleOutlined',
  'PlusOutlined',
  'PlusSquareOutlined',
  'PoundCircleOutlined',
  'PoundOutlined',
  'PoweroffOutlined',
  'PrinterOutlined',
  'ProfileOutlined',
  'ProjectOutlined',
  'PropertySafetyOutlined',
  'PullRequestOutlined',
  'PushpinOutlined',
  'QqOutlined',
  'QrcodeOutlined',
  'QuestionCircleOutlined',
  'QuestionOutlined',
  'RadarChartOutlined',
  'RadiusBottomleftOutlined',
  'RadiusBottomrightOutlined',
  'RadiusSettingOutlined',
  'RadiusUpleftOutlined',
  'RadiusUprightOutlined',
  'ReadOutlined',
  'ReconciliationOutlined',
  'RedEnvelopeOutlined',
  'RedditOutlined',
  'RedoOutlined',
  'ReloadOutlined',
  'RestOutlined',
  'RetweetOutlined',
  'RightCircleOutlined',
  'RightOutlined',
  'RightSquareOutlined',
  'RiseOutlined',
  'RobotOutlined',
  'RocketOutlined',
  'RollbackOutlined',
  'RotateLeftOutlined',
  'RotateRightOutlined',
  'SafetyCertificateOutlined',
  'SafetyOutlined',
  'SaveOutlined',
  'ScanOutlined',
  'ScheduleOutlined',
  'ScissorOutlined',
  'SearchOutlined',
  'SecurityScanOutlined',
  'SelectOutlined',
  'SendOutlined',
  'SettingOutlined',
  'ShakeOutlined',
  'ShareAltOutlined',
  'ShopOutlined',
  'ShoppingCartOutlined',
  'ShoppingOutlined',
  'ShrinkOutlined',
  'SisternodeOutlined',
  'SketchOutlined',
  'SkinOutlined',
  'SkypeOutlined',
  'SlackOutlined',
  'SlackSquareOutlined',
  'SlidersOutlined',
  'SmallDashOutlined',
  'SmileOutlined',
  'SnippetsOutlined',
  'SolutionOutlined',
  'SortAscendingOutlined',
  'SortDescendingOutlined',
  'SoundOutlined',
  'SplitCellsOutlined',
  'StarOutlined',
  'StepBackwardOutlined',
  'StepForwardOutlined',
  'StockOutlined',
  'StopOutlined',
  'StrikethroughOutlined',
  'SubnodeOutlined',
  'SwapLeftOutlined',
  'SwapOutlined',
  'SwapRightOutlined',
  'SwitcherOutlined',
  'SyncOutlined',
  'TableOutlined',
  'TabletOutlined',
  'TagOutlined',
  'TagsOutlined',
  'TaobaoCircleOutlined',
  'TaobaoOutlined',
  'TeamOutlined',
  'ThunderboltOutlined',
  'ToTopOutlined',
  'ToolOutlined',
  'TrademarkCircleOutlined',
  'TrademarkOutlined',
  'TransactionOutlined',
  'TranslationOutlined',
  'TrophyOutlined',
  'TwitterOutlined',
  'UnderlineOutlined',
  'UndoOutlined',
  'UngroupOutlined',
  'UnlockOutlined',
  'UnorderedListOutlined',
  'UpCircleOutlined',
  'UpOutlined',
  'UpSquareOutlined',
  'UploadOutlined',
  'UsbOutlined',
  'UserAddOutlined',
  'UserDeleteOutlined',
  'UserOutlined',
  'UserSwitchOutlined',
  'UsergroupAddOutlined',
  'UsergroupDeleteOutlined',
  'VerifiedOutlined',
  'VerticalAlignBottomOutlined',
  'VerticalAlignMiddleOutlined',
  'VerticalAlignTopOutlined',
  'VerticalLeftOutlined',
  'VerticalRightOutlined',
  'VideoCameraAddOutlined',
  'VideoCameraOutlined',
  'WalletOutlined',
  'WarningOutlined',
  'WechatOutlined',
  'WeiboCircleOutlined',
  'WeiboOutlined',
  'WeiboSquareOutlined',
  'WhatsAppOutlined',
  'WifiOutlined',
  'WindowsOutlined',
  'WomanOutlined',
  'YahooOutlined',
  'YoutubeOutlined',
  'YuqueOutlined',
  'ZhihuOutlined',
  'ZoomInOutlined',
  'ZoomOutOutlined',
] as const

type OutlineIconName = (typeof outlinedIconNames)[number]

export type IconKey = string

export type IconOption = {
  label: string
  value: IconKey
  component: OutlineIconName
  category: SelectableIconCategoryKey
}

const commonIconNames = new Set<OutlineIconName>([
  'AppstoreOutlined',
  'BookOutlined',
  'BulbOutlined',
  'CalendarOutlined',
  'ClockCircleOutlined',
  'DatabaseOutlined',
  'EditOutlined',
  'FileTextOutlined',
  'FolderOutlined',
  'HomeOutlined',
  'InboxOutlined',
  'PaperClipOutlined',
  'ProfileOutlined',
  'ProjectOutlined',
  'PushpinOutlined',
  'ReadOutlined',
  'SettingOutlined',
  'SnippetsOutlined',
  'StarOutlined',
  'TagsOutlined',
  'TeamOutlined',
  'ToolOutlined',
  'UserOutlined',
])

const keywordGroups: Array<{ category: SelectableIconCategoryKey; words: string[] }> = [
  {
    category: 'brand',
    words: [
      'alibaba', 'alipay', 'aliwangwang', 'aliyun', 'amazon', 'android', 'antcloud', 'antdesign',
      'apple', 'behance', 'chrome', 'codepen', 'dingding', 'dingtalk', 'dribbble', 'dropbox',
      'facebook', 'github', 'gitlab', 'google', 'html5', 'instagram', 'linkedin', 'medium',
      'qq', 'reddit', 'skype', 'slack', 'taobao', 'twitter', 'wechat', 'weibo', 'whatsapp',
      'windows', 'yahoo', 'youtube', 'yuque', 'zhihu',
    ],
  },
  {
    category: 'document',
    words: [
      'file', 'folder', 'book', 'read', 'profile', 'snippet', 'paperclip', 'container', 'contacts',
      'solution', 'schedule', 'audit', 'reconciliation', 'idcard', 'exception', 'diff', 'carryout',
      'form', 'printer', 'save', 'scan', 'copy',
    ],
  },
  {
    category: 'data',
    words: [
      'chart', 'database', 'table', 'barcode', 'qrcode', 'calculator', 'number', 'field', 'fund',
      'stock', 'percentage', 'boxplot', 'dotchart', 'radarchart', 'heatmap', 'function', 'console',
      'partition', 'cluster', 'nodeindex',
    ],
  },
  {
    category: 'dev',
    words: [
      'api', 'bug', 'code', 'cloud', 'server', 'deployment', 'desktop', 'laptop', 'mobile', 'monitor',
      'robot', 'rocket', 'usb', 'wifi', 'branches', 'fork', 'pullrequest', 'gateway', 'hdd', 'global',
      'disconnect', 'interaction', 'apartment', 'experiment',
    ],
  },
  {
    category: 'editor',
    words: [
      'align', 'bold', 'italic', 'underline', 'strikethrough', 'font', 'highlight', 'bgcolors',
      'border', 'layout', 'orderedlist', 'unorderedlist', 'lineheight', 'pic', 'insertrow',
      'deleterow', 'deletecolumn', 'mergecells', 'splitcells', 'formatpainter', 'columnheight',
      'columnwidth', 'radius', 'scissor', 'skin', 'translation', 'smallDash',
    ],
  },
  {
    category: 'media',
    words: [
      'audio', 'sound', 'camera', 'picture', 'video', 'play', 'pause', 'forward', 'backward', 'gif',
      'fullscreen', 'zoom', 'customer', 'notification', 'bell',
    ],
  },
  {
    category: 'communication',
    words: ['mail', 'message', 'comment', 'phone', 'send', 'share', 'shake', 'notification', 'bell'],
  },
  {
    category: 'navigation',
    words: [
      'arrow', 'caret', 'down', 'up', 'left', 'right', 'menu', 'ellipsis', 'more', 'login', 'logout',
      'import', 'export', 'download', 'upload', 'search', 'filter', 'sort', 'rollback', 'undo', 'redo',
      'reload', 'sync', 'swap', 'enter', 'expand', 'compress', 'shrink', 'vertical', 'totop', 'step',
      'double', 'select', 'drag', 'holder',
    ],
  },
  {
    category: 'status',
    words: [
      'alert', 'check', 'close', 'info', 'warning', 'question', 'exclamation', 'stop', 'lock', 'unlock',
      'safety', 'security', 'fire', 'heart', 'like', 'dislike', 'smile', 'frown', 'meh', 'star', 'trophy',
      'crown', 'verified', 'insurance', 'medicine', 'property', 'poweroff', 'rest', 'eye', 'loading',
      'minus', 'plus', 'clear',
    ],
  },
  {
    category: 'work',
    words: [
      'account', 'aim', 'appstore', 'bank', 'build', 'car', 'creditcard', 'dashboard', 'dollar', 'euro',
      'gold', 'home', 'inbox', 'money', 'pay', 'pound', 'project', 'redEnvelope', 'shop', 'shopping',
      'team', 'transaction', 'user', 'wallet', 'apartment', 'environment', 'control', 'crown', 'gift',
    ],
  },
]

const legacyIconOptions: IconOption[] = [
  { label: '\u7b14\u8bb0', value: 'note', component: 'FileTextOutlined', category: 'common' },
  { label: '\u4e66\u672c', value: 'book', component: 'BookOutlined', category: 'common' },
  { label: '\u6587\u4ef6\u5939', value: 'folder', component: 'FolderOutlined', category: 'document' },
  { label: '\u6587\u4ef6', value: 'file', component: 'FileOutlined', category: 'document' },
  { label: '\u7f16\u8f91', value: 'edit', component: 'EditOutlined', category: 'editor' },
  { label: '\u6807\u7b7e', value: 'tag', component: 'TagsOutlined', category: 'common' },
  { label: '\u661f\u6807', value: 'star', component: 'StarOutlined', category: 'common' },
  { label: '\u56fe\u9489', value: 'pin', component: 'PushpinOutlined', category: 'common' },
  { label: '\u65e5\u5386', value: 'calendar', component: 'CalendarOutlined', category: 'common' },
  { label: '\u65f6\u949f', value: 'clock', component: 'ClockCircleOutlined', category: 'common' },
  { label: '\u7075\u611f', value: 'idea', component: 'BulbOutlined', category: 'common' },
  { label: '\u9605\u8bfb', value: 'read', component: 'ReadOutlined', category: 'document' },
  { label: '\u8d44\u6599', value: 'profile', component: 'ProfileOutlined', category: 'document' },
  { label: '\u7247\u6bb5', value: 'snippets', component: 'SnippetsOutlined', category: 'document' },
  { label: '\u9644\u4ef6', value: 'attachment', component: 'PaperClipOutlined', category: 'document' },
  { label: '\u6536\u7eb3', value: 'inbox', component: 'InboxOutlined', category: 'common' },
  { label: '\u6570\u636e', value: 'database', component: 'DatabaseOutlined', category: 'data' },
  { label: '\u5e94\u7528', value: 'app', component: 'AppstoreOutlined', category: 'common' },
  { label: '\u9879\u76ee', value: 'project', component: 'ProjectOutlined', category: 'work' },
  { label: '\u5b9e\u9a8c', value: 'lab', component: 'ExperimentOutlined', category: 'dev' },
  { label: '\u4ee3\u7801', value: 'code', component: 'CodeOutlined', category: 'dev' },
  { label: '\u5de5\u5177', value: 'tool', component: 'ToolOutlined', category: 'common' },
  { label: '\u8bbe\u7f6e', value: 'settings', component: 'SettingOutlined', category: 'common' },
  { label: '\u4e3b\u9875', value: 'home', component: 'HomeOutlined', category: 'common' },
  { label: '\u7528\u6237', value: 'user', component: 'UserOutlined', category: 'common' },
  { label: '\u56e2\u961f', value: 'team', component: 'TeamOutlined', category: 'common' },
  { label: '\u559c\u6b22', value: 'heart', component: 'HeartOutlined', category: 'status' },
  { label: '\u5fae\u7b11', value: 'smile', component: 'SmileOutlined', category: 'status' },
  { label: '\u5496\u5561', value: 'coffee', component: 'CoffeeOutlined', category: 'media' },
  { label: '\u542f\u52a8', value: 'rocket', component: 'RocketOutlined', category: 'dev' },
  { label: '\u672a\u77e5', value: 'unknown', component: 'QuestionCircleOutlined', category: 'status' },
]

function humanize(component: string) {
  return component
    .replace(/Outlined$/, '')
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2')
}

function toKebab(component: string) {
  return humanize(component).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}

function inferCategory(component: OutlineIconName): SelectableIconCategoryKey {
  if (commonIconNames.has(component)) return 'common'
  const normalized = component.replace(/Outlined$/, '').toLowerCase()
  return keywordGroups.find((group) => group.words.some((word) => normalized.includes(word.toLowerCase())))?.category ?? 'common'
}

const generatedIconOptions = outlinedIconNames.map((component): IconOption => ({
  label: humanize(component),
  value: toKebab(component),
  component,
  category: inferCategory(component),
}))

const seenIconValues = new Set<string>()

export const iconOptions: IconOption[] = [...legacyIconOptions, ...generatedIconOptions].filter((option) => {
  if (seenIconValues.has(option.value)) return false
  seenIconValues.add(option.value)
  return true
})

export const iconMap = Object.fromEntries(
  iconOptions.map((option) => [option.value, componentMap[option.component]]),
) as Record<IconKey, Component>

export function getIconOption(value?: string) {
  if (!value) return undefined
  return iconOptions.find((option) => option.value === value)
}
